  push:
    tags:
      - 'test-helm-chart-[0-9]+.[0-9]+.[0-9]+'

jobs:
  releases-matrix:
    name: Release Go binaries
    permissions:
      contents: write
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, windows, darwin]
        goarch: [amd64, arm, arm64]
        exclude:
          - goarch: arm
            goos: windows
          - goarch: arm64
            goos: windows
          - goarch: arm
            goos: darwin
    steps:
      - uses: actions/checkout@v3
      - name: Get version
        id: get_version
        run: echo "version=${GITHUB_REF#refs/tags/test-helm-chart-}" >> $GITHUB_OUTPUT
      - uses: wangyoucao577/go-release-action@v1.35
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goos: ${{ matrix.goos }}
          goarch: ${{ matrix.goarch }}
          release_tag: ${{ steps.get_version.outputs.version }}
          ldflags: -X main.version=${{ steps.get_version.outputs.version }}
